project_id = "pvtppgnwhkbihsnfzvym"

[functions.generate-interview-guide]
verify_jwt = false

[functions.generate-smart-ad]
verify_jwt = false

[functions.generate-job-profile]
verify_jwt = false

[functions.generate-job-ad]
verify_jwt = false

[functions.generate-interview-kit]
verify_jwt = false

[functions.generate-onboarding-plan]
verify_jwt = false

[functions.analyze-candidates]
verify_jwt = false
